import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "El blog de un programador - Felipe Bolgar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-neutral-800 text-white ${inter.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
